### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [62]:
# ciclo 1)
#for classico

l1 = []
for n in range(5):
    if (n%2 == 0):
        l1.append(n)

print(l1)

#versione con list comprehension

l1 = [n for n in range(5) if n%2 == 0]

print("l1 con comprehension:", l1)

print("- - - - - - - - - - - - -")

l1.clear()

# ciclo 2)

check = lambda a: (a**2 - (a-1)**2) > 2


for numero in range(10):
    if check(numero):
        l1.append(numero**2)

print(l1)

#versione con list comprehension

l1 = [n**2 for n in range(10) if check(n)]
print("l1 con comprehension:", l1)


print("- - - - - - - - - - - - -")


l1.clear()

my_dict = {"a":[1,6,3],"b":[9,1,2],"c":[2,5,1]}

for key in my_dict:
    for value in my_dict[key]:
        if value%2 == 0:
            l1.append(value)

print(l1)

l1= [value for sublist in my_dict for value in my_dict[sublist] if value%2 == 0]

print("l1 con comprehension:", l1)




[0, 2, 4]
l1 con comprehension: [0, 2, 4]
- - - - - - - - - - - - -
[4, 9, 16, 25, 36, 49, 64, 81]
l1 con comprehension: [4, 9, 16, 25, 36, 49, 64, 81]
- - - - - - - - - - - - -
[6, 2, 2]
l1 con comprehension: [6, 2, 2]


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [66]:
import numpy as np

#1

array_1 = np.array([2,3,5,7])

#2

print(len(array_1))
print(array_1.size)

#3
#il vettore sarà intero

print("Il vettore è di tipo: ", array_1.dtype)

#4

def is_primo(i):

    for x in range(2, i-1):
        if i%x == 0:
            return False
    return True


a = np.array([i for i in range(2,10) if is_primo(i)])


a

4
4
Il vettore è di tipo:  int64


array([2, 3, 5, 7])

### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [21]:
a = np.arange(1,20)
b = a[2:4]
c = a[::-1]

print(f"I 3 Array iniziali: \n {a} \n {b} \n {c} \n")

print("A diviso C = \n", a/c)

al =[1,2,3,4]
alb = al[::-1]

print("\n alb= ",alb)

for i,j in zip(al,alb):
    print("\n al/alb =", i/j)





I 3 Array iniziali: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 
 [3 4] 
 [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1] 

A diviso C = 
 [ 0.05263158  0.11111111  0.17647059  0.25        0.33333333  0.42857143
  0.53846154  0.66666667  0.81818182  1.          1.22222222  1.5
  1.85714286  2.33333333  3.          4.          5.66666667  9.
 19.        ]

 alb=  [4, 3, 2, 1]

 al/alb = 0.25

 al/alb = 0.6666666666666666

 al/alb = 1.5

 al/alb = 4.0
