In [8]:
print ("hellow orld!")

hellow orld!


"Qui scrivo testo."

In [ ]:
x = 2 + 2
print("ciao")

ciao


In [14]:
print(2+2)
print("hello world")

4
hello world


In [ ]:
"così interagisco direttamente col terminale: ![comando]"
"ma ricorda che ogni volta che lo faccio, azzera i comandi che ho eseguito sullo shell prima"


In [15]:
%timeit [n*n for n in range(200)]

11.3 μs ± 291 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


spaziatura di python corretta:

In [17]:
def greet(name):
    """ questa funzione dà il nome della persona passata in argomento """
    print(name)

help(greet)

Help on function greet in module __main__:

greet(name)
    questa funzione dà il nome della persona passata in argomento



Lo slicing non torna mai errore:

In [18]:
lista = []
lista2 = [2,3]
stringa =""

lista[:], lista2[1:4], stringa[1:2]

([], [3], '')

In [19]:
jobs_data = [
    {'job_title': 'Data Scientist',  'job_skills': ['Python', 'Machine Learning'], 'remote': True},
    {'job_title': 'Data Analyst',  'job_skills': ['Excel', 'SQL'], 'remote': False},
    {'job_title': 'Machine Learning Engineer', 'job_skills': ['Python', 'TensorFlow', 'Keras'], 'remote': True},
    {'job_title': 'Software Developer', 'job_skills': ['Java', 'C++'], 'remote': True},
    {'job_title': 'Data Scientist', 'job_skills': ['R', 'Statistics'], 'remote': False}
]

In [ ]:
list(filter(lambda job: job["remote"], jobs_data))

[{'job_title': 'Data Scientist',
  'job_skills': ['Python', 'Machine Learning'],
  'remote': True},
 {'job_title': 'Machine Learning Engineer',
  'job_skills': ['Python', 'TensorFlow', 'Keras'],
  'remote': True},
 {'job_title': 'Software Developer',
  'job_skills': ['Java', 'C++'],
  'remote': True}]

Come creo un modulo python:

In [ ]:
%%writefile my_module.py

def somma(x,y):
    return x+y



Overwriting my_module.py


Come lo modifico:

In [ ]:
%%writefile -a my_module.py

def somma_new(x,y):
    return x+y



Appending to my_module.py


In [33]:
import my_module

print(my_module.somma(3,2))

5


VEDIAMO LE LIBRERIE DI TERZE PARTI

PANDAS

In [ ]:
import pandas as pd

dataframe = pd.read_csv

NUMPY --> FONDAMENTALE PER DATA SCIENCE (in quanto permette di lavorare su matrici, che è fondamentale per l'analisi dei dati)

In [2]:
import numpy as np

np.mean([2,3,4])

np.float64(3.0)

ARRAY SU NUMPY
HANNO DATI TUTTI DELLO STESSO TIPO.

In [ ]:
np.array([1, 2.2 ,3]).dtype #questo è di tipo float

np.array([1,2,"a"]).dtype  #questo è di tipo unicode stringa

dtype('<U21')


a.shape ritorna una tupla con le dimensioni dell’array (con un elemento nel caso di un vettore, due per le matrici, etc)

a.size ritorna il numero di elementi totali (e.g., una matrice 4x3 avrà  12 elementi e shape (4,3))

Con a.astype(nome_tipo) possiamo convertire al tipo numpy indicato

# Esempio di generazione di array
a = np.arange(10)

In [5]:
np.arange(0.4,0.8,0.1)

array([0.4, 0.5, 0.6, 0.7])

In [6]:

np.linspace(0.5,0.7,3)

array([0.5, 0.6, 0.7])

AZZERAMENTO

In [13]:
np.zeros(3)

a = np.arange(1,10,2)
a

a = np.zeros(a)
a

array([[[[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0

OPERAZIONI SUGLI ARRAY

In [37]:
a = np.arange(1,10,2)
a
print(a)
b = a * 2
print(b)

[1 3 5 7 9]
[ 2  6 10 14 18]


PER COPIARE

In [ ]:
b = a #INCORRETTO

b = a.copy()

In [ ]:
a=np.array([1,3,7])

print(len(a))




3
